Should not have to run this again since data is saved csv file now

In [ ]:
# from get_gss.ipynb, provided code to get just needed variables

output_filename = 'selected_gss_data.csv' # Name of the file you want to save the data to

modes = ['w','a'] # Has write mode and append mode
phase = 0 # Starts in write mode; after one iteration of loop, switches to append mode

for k in range(3): # for each chunk of the data
    # Create url to the chunk to be processed
    url = 'https://github.com/kaykizzzle/ML-project-1/raw/main/gss_chunk_' + str(1+k) + '.parquet'
    print(url) # Check the url is correct
    df = pd.read_parquet(url) # Download this chunk of data
    print(df.head()) # Visually inspect the first few rows
    df.loc[:,var_list].to_csv(output_filename, # specifies target file to save the chunk to
                              mode=modes[phase], # control write versus append
                              header=var_list, # variable names
                              index=False) # no row index saved
    phase = 1 # Switch from write mode to append mode

https://github.com/kaykizzzle/ML-project-1/raw/main/gss_chunk_1.parquet
   year  id            wrkstat  hrs1  hrs2 evwork    occ  prestige  \
0  1972   1  working full time   NaN   NaN    NaN  205.0      50.0
1  1972   2            retired   NaN   NaN    yes  441.0      45.0
2  1972   3  working part time   NaN   NaN    NaN  270.0      44.0
3  1972   4  working full time   NaN   NaN    NaN    1.0      57.0
4  1972   5      keeping house   NaN   NaN    yes  385.0      40.0

         wrkslf wrkgovt  ...  agehef12 agehef13 agehef14  hompoph wtssps_nea  \
0  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
1  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
2  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
3  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
4  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN

   wtssnrps_nea  wtssps_next wtssnrps_next wtsscomp wtsscompnr
0           NaN          NaN           NaN   0.4446        NaN
1           NaN          NaN           NaN   0.8893        NaN
2           NaN          NaN           NaN   0.8893        NaN
3           NaN          NaN           NaN   0.8893        NaN
4           NaN          NaN           NaN   0.8893        NaN

[5 rows x 6694 columns]
https://github.com/kaykizzzle/ML-project-1/raw/main/gss_chunk_2.parquet
   year   id            wrkstat  hrs1  hrs2 evwork    occ  prestige  \
0  1989  775            retired   NaN   NaN    yes  540.0      36.0
1  1989  776  working full time  40.0   NaN    NaN  925.0      36.0
2  1989  777            retired   NaN   NaN    yes   80.0      61.0
3  1989  778  working full time  44.0   NaN    NaN  912.0      26.0
4  1989  779            retired   NaN   NaN    yes  690.0      32.0

         wrkslf wrkgovt  ...  agehef12 agehef13 agehef14  hompoph wtssps_nea  \
0  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
1  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
2  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
3  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN
4  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN

   wtssnrps_nea  wtssps_next wtssnrps_next  wtsscomp wtsscompnr
0           NaN          NaN           NaN  1.295069        NaN
1           NaN          NaN           NaN  0.483624        NaN
2           NaN          NaN           NaN  0.407988        NaN
3           NaN          NaN           NaN  1.225988        NaN
4           NaN          NaN           NaN  0.504302        NaN

[5 rows x 6694 columns]
https://github.com/kaykizzzle/ML-project-1/raw/main/gss_chunk_3.parquet
   year    id            wrkstat  hrs1  hrs2 evwork  occ  prestige  \
0  2006  1751  working full time  40.0   NaN    NaN  NaN       NaN
1  2006  1752          in school   NaN   NaN    yes  NaN       NaN
2  2006  1753  working full time  35.0   NaN    NaN  NaN       NaN
3  2006  1754  working full time  50.0   NaN    NaN  NaN       NaN
4  2006  1755  working full time  40.0   NaN    NaN  NaN       NaN

         wrkslf     wrkgovt  ...  agehef12 agehef13 agehef14  hompoph  \
0  someone else  government  ...       NaN      NaN      NaN      NaN
1  someone else     private  ...       NaN      NaN      NaN      NaN
2  someone else  government  ...       NaN      NaN      NaN      NaN
3  someone else  government  ...       NaN      NaN      NaN      NaN
4  someone else     private  ...       NaN      NaN      NaN      NaN

  wtssps_nea  wtssnrps_nea  wtssps_next wtssnrps_next  wtsscomp wtsscompnr
0        NaN           NaN          NaN           NaN  1.079141   0.961150
1        NaN           NaN          NaN           NaN  7.673834   6.641571
2        NaN           NaN          NaN           NaN  0.584663   0.512145
3        NaN           NaN          NaN           NaN  0.715731   0.637592
4        NaN           NaN          NaN           NaN  1.094831   0.956094

[5 rows x 6694 columns]

**RUN STARTING FORM HERE**

**Relevant Variables:**

| Variable | Definition |                       
| :---------:| :---------- |  
| year     | year observation was taken |  
| occ10    | occupation of the patient |  
| marital  | participant's marital status |  
| martype  | type of marriage             |  
| age      | age of the participant       |  
| educ     | respondent’s education (numeric variable) |  
| major1   | area or field of study when degree was obtained (highest degree obtained)|  
| sex      | biological sex            |  
| race     | what race the participant considers themselves              |  
| satfin   |  participant’s financial satisfaction (considering themselves and their family)|
| pres20   | who did the respondent vote for in the 2020 election (Biden or Trump)|  
| eqwlth   | should the government reduce income differences (numeric: 1 = the government should reduce income differences; 7 = government should not concern itself with reducing income differences)|        
| tax      | thoughts about income tax (too high, too low, or about right)|  
| relig    | religious preference |
| fepol    | men are better suited emotionally for politics than most women (agree or disagree)|
| owngun   | any guns/revolvers in the house (or garage)|
| helpnot  |  the government should be doing more (to solve problems in our country) or are they doing too much (puts more emphasis on individuals and private businesses); 1 = government should do more; 3 = agree with both; 5 = government does too much|
| sexfreq  | frequency of sexual intercourse over the last 12 months|
| childs   | number of children the participant ever had|
| helpful  | do people try to be helpful or are they looking out for themselves?|
| confinan*  | bank and financial institutions |
| conbus*    | major companies|
| conclerg*  | organized religion|
| coneduc*   | education |
| confed*    | executive branch of the federal government|
| conlabor*  | organized labor|
| conpress*  | press|
| conmedic*  | medicine|
| conjudge*  | U.S. Supreme Court|
| consci*    | scientific community|
| conlegis*  | Congress|
| conarmy*   | military|

(*) These variables measure the respondent's confidence in an institution

**Data Cleaning:**

In [ ]:
# import relevant packages, RUN THIS and code chunks below
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# imports selected gss data from csv file
df = pd.read_csv('selected_gss_data.csv',low_memory=False)

# List of variables
var_list = ['year','occ10','marital','martype','age','educ','major1','sex','race','satfin','pres20','eqwlth','tax','relig','confinan','conbus','conclerg','coneduc','confed','conlabor','conpress','conmedic','conjudge','consci','conlegis','conarmy','conpharvac','fepol','owngun','helpnot','hlthdep','hlthconf','sexfreq','childs','helpful']

In [ ]:
df.shape

(72392, 35)

In [ ]:
df.describe()

,year,occ10,marital,martype,age,educ,major1,sex,race,satfin,pres20,eqwlth,tax,relig,confinan,conbus,conclerg,coneduc,confed,conlabor,conpress,conmedic,conjudge,consci,conlegis,conarmy,conpharvac,fepol,owngun,helpnot,hlthdep,hlthconf,sexfreq,childs,helpful
count,72392,67254,72341,5076,71623,72129,7227,72280,72285,67724,2398,38760,40250,71955,45241,47260,47383,48402,47729,46405,48085,48503,47168,45754,47700,47804,1164,35699,45865,36777,1129,1134,34521,72131,42221
unique,35,534,6,4,73,22,82,3,4,4,5,8,5,14,4,4,4,4,4,4,4,4,4,4,4,4,4,3,4,6,6,6,8,10,4
top,2006,secretaries and administrative assistants,married,marriage between a man and a woman,30.0,12.0,business administration,female,white,more or less satisfied,biden,1.0,too high,protestant,only some,only some,only some,only some,only some,only some,only some,only some,only some,only some,only some,only some,a great deal,disagree,no,3.0,never,never,not at all,0.0,try to be helpful
freq,4510,2727,37590,4999,1571,21401,1072,40301,57657,29987,1417,8386,24553,40125,25437,29007,24226,27230,23870,26278,24600,22308,24735,22537,25874,22099,541,25715,27551,14779,386,556,7977,19927,20466

In [ ]:
# remove 2 instances of 'varname' from varname from every variable
for var in var_list:
    string = str(var)
    df[string] = df[string].replace(string,np.nan)

df['owngun'] = df['owngun'].replace('refused_(3)', 'refused') # rename confusing variable name

> The data are actually pretty clean besides the 2 weird instances of the var name in most of the variables. While not shown here for space/repition reasons, every variable was looked at with 'value_counts()' and 'describe()'. Additional cleaning is more dependent on what questions are asked and what variables are analyzed. There are a large number of NANs because some of the questions are not asked every year. The confidence questions (our main analysis variables) generally have 40-50k responses (except 'conpharvac'), so it is likely we will only look at the observations that have responses for those questions by narrowing the data with the 'year' variable.

In [ ]:
# creating data subset of years that have responses to confidence questions (1973-1984 && 1986-2022)
start_year_index1 = df[df.year == '1973'].index[0]
end_year_index1 = df[df.year == '1985'].index[0]
start_year_index2 = df[df.year == '1986'].index[0]

df_subset1 = df.iloc[int(start_year_index1):int(end_year_index1)] # first data subset from 1973-1984
df_subset2 = df.iloc[int(start_year_index2):-1] # second data subset from 1986-2022
df_subset = pd.concat([df_subset1,df_subset2]) # merges both subsets into complete dataset with years where confidence questions were asked

pd.set_option('display.max_columns', None) # makes sure all columns are displayed

In [ ]:
# remove 'conpharvac', 'hlthdep', and 'hlthconf' due to low observation count
# leaving 'pres20' in because it is data from just 1 year so it will be low, plus could be interesting to analyze
df_subset = df_subset.drop(['conpharvac','hlthdep','hlthconf'],axis=1)

print(df_subset.shape)
df_subset.describe()

(69244, 32)

,year,occ10,marital,martype,age,educ,major1,sex,race,satfin,pres20,eqwlth,tax,relig,confinan,conbus,conclerg,coneduc,confed,conlabor,conpress,conmedic,conjudge,consci,conlegis,conarmy,fepol,owngun,helpnot,sexfreq,childs,helpful
count,69242,64558,69191,5073,68485,68984,7224,69130,69135,64588,2395,38757,38764,68815,45238,47257,47380,48399,47726,46402,48082,48500,47165,45751,47697,47801,34230,44333,36774,34518,68993,40629
unique,32,533,5,3,72,21,81,2,3,3,4,7,4,13,3,3,3,3,3,3,3,3,3,3,3,3,2,3,5,7,9,3
top,2006,secretaries and administrative assistants,married,marriage between a man and a woman,32.0,12.0,business administration,female,white,more or less satisfied,biden,1.0,too high,protestant,only some,only some,only some,only some,only some,only some,only some,only some,only some,only some,only some,only some,disagree,no,3.0,not at all,0.0,try to be helpful
freq,4510,2581,35558,4998,1492,20383,1072,38649,54970,28596,1416,8386,23628,38139,25436,29006,24225,27229,23869,26277,24600,22308,24735,22537,25873,22099,24814,26709,14778,7977,19124,19716

**Data Exploration:**

**Data Analysis:**